### ISSUE TITLE
Panic while handling bff call defined in configuration request.

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/deriv-api-bff#35]
The application is panicking if we get error while sending requests to Deriv backend

```
deriv-api-bff  | panic: runtime error: range function continued iteration after function for loop body returned false
deriv-api-bff  | 
deriv-api-bff  | goroutine 45 [running]:
deriv-api-bff  | github.com/ksysoev/deriv-api-bff/pkg/core/handler.(*Handler).Handle-range1({0x400023a930, 0x400000c318, {0x4000107540, 0x2f, 0x40}, 0xf4242})
deriv-api-bff  |        /app/pkg/core/handler/handler.go:67 +0x178
deriv-api-bff  | github.com/ksysoev/deriv-api-bff/pkg/core/handler.(*Handler).Handle.(*Handler).requests.func1(0x4000223d38)
deriv-api-bff  |        /app/pkg/core/handler/handler.go:109 +0x90
deriv-api-bff  | github.com/ksysoev/deriv-api-bff/pkg/core/handler.(*Handler).Handle(0x40001ccf30, {0x62a490, 0x40001001e0}, 0x400010b8f0, 0x4000118850, 0x400034aea0)
deriv-api-bff  |        /app/pkg/core/handler/handler.go:67 +0x188
deriv-api-bff  | github.com/ksysoev/deriv-api-bff/pkg/core.(*Service).ProcessRequest(0x40001ccf60, {0x62a810, 0x400013e000}, 0x400016f920)
deriv-api-bff  |        /app/pkg/core/svc.go:69 +0x13c
deriv-api-bff  | github.com/ksysoev/deriv-api-bff/pkg/api.(*Service).Handle(0x40000b8d40?, {0x62a810?, 0x400013e000?}, {0x62a730?, 0x400016f920?})
deriv-api-bff  |        /app/pkg/api/svc.go:93 +0xd0
deriv-api-bff  | github.com/ksysoev/wasabi/dispatch.(*RouterDispatcher).Dispatch(0x40000b8d40, {0x62a810, 0x400013e000}, 0x1, {0x4000210000, 0x5b, 0x400})
deriv-api-bff  |        /go/pkg/mod/github.com/ksysoev/wasabi@v0.5.1/dispatch/router_dipatcher.go:58 +0x108
deriv-api-bff  | github.com/ksysoev/wasabi/channel.(*Conn).handleRequests.func1(0x0?)
deriv-api-bff  |        /go/pkg/mod/github.com/ksysoev/wasabi@v0.5.1/channel/connection.go:133 +0x94
deriv-api-bff  | created by github.com/ksysoev/wasabi/channel.(*Conn).handleRequests in goroutine 33
deriv-api-bff  |        /go/pkg/mod/github.com/ksysoev/wasabi@v0.5.1/channel/connection.go:131 +0x1ac
deriv-api-bff exited with code 2
```

**Comment by shan-96** [comment]
```go
      for req := range h.requests(ctx, params, watcher) {
		comp.Wait(ctx, req.parser, req.respChan)

----->	if err := send(ctx, req.data); err != nil {
			return nil, fmt.Errorf("failed to send request: %w", err)
		}
	}
```

you can break out of the loop and return from there it might work. Can you give me sample request? I will try on my patch
