### ISSUE TITLE
etcd mocks find better way to generate mock

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/deriv-api-bff#56]
Current mockery configuration is broken. we need to find way to generate mocks for external packages to generate them as out package, while internal interfaces are generated as in package

```
failed to open output file for mock: /Users/kirill/go/pkg/mod/go.etcd.io/etcd@v3.3.27+incompatible/clientv3/kv_mock.go: open /Users/kirill/go/pkg/mod/go.etcd.io/etcd@v3.3.27+incompatible/clientv3/kv_mock.go: permission denied
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x64
github.com/vektra/mockery/v2/pkg/stackerr.NewStackErr(...)
        github.com/vektra/mockery/v2/pkg/stackerr/stackerr.go:17
github.com/vektra/mockery/v2/pkg/stackerr.NewStackErrf({0x105380b08, 0x140020e9170}, {0x1051d3e34?, 0x0?}, {0x14001817228?, 0x140020ee000?, 0xf9?})
        github.com/vektra/mockery/v2/pkg/stackerr/stackerr.go:24 +0xa0
github.com/vektra/mockery/v2/pkg.(*Outputter).Generate(0x14001817c90, {0x105385718, 0x14001c82ba0}, 0x1400103dd50)
        github.com/vektra/mockery/v2/pkg/outputter.go:371 +0x8f8
github.com/vektra/mockery/v2/cmd.(*RootApp).Run(0x140001765a0)
        github.com/vektra/mockery/v2/cmd/mockery.go:269 +0x1754
github.com/vektra/mockery/v2/cmd.NewRootCmd.func1(0x14000168e00?, {0x1051a068c?, 0x4?, 0x1051a0690?})
        github.com/vektra/mockery/v2/cmd/mockery.go:46 +0x48
github.com/spf13/cobra.(*Command).execute(0x1400017e908, {0x1400001e180, 0x0, 0x0})
        github.com/spf13/cobra@v1.6.1/command.go:920 +0x630
github.com/spf13/cobra.(*Command).ExecuteC(0x1400017e908)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/vektra/mockery/v2/cmd.Execute()
        github.com/vektra/mockery/v2/cmd/mockery.go:106 +0x20
main.main()
        github.com/vektra/mockery/v2/main.go:8 +0x1c

make: *** [mocks] Error 1
```

as alternative we can implement thin adapter layer that will be hidden behind interface and test this thin layer with integration tests

**Comment by ksysoev** [comment]
Let's finish implementation of hot reload, then it'll be easier to refactor

**Comment by shan-96** [comment]
@ksysoev I managed to fix it by following changes.

1. modify the mockery yaml as
```yaml
inpackage: false
dir: ./mocks
outpkg: mocks
```
2. Then I noticed some cyclic dependency problem so I changed test source to be in package `${main_pkg}_test`

let me know if this is ok

**Comment by ksysoev** [comment]
@shan-96 wait a bit on this

**Comment by ksysoev** [comment]
It will be sorted in #81 I'm replacing mocks with integration tests for etcd source
